version: '3.7'

services:
  postgres:
    build:
      context: ./
      dockerfile: docker/development/postgres/Dockerfile
    container_name: learner_linkup_postgres
    ports:
      - '5444:5432'
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
        learner-linkup-network:
          ipv4_address: 192.168.20.200
    tmpfs:
      - /var/lib/postgresql/data

networks:
  learner-linkup-network:
    name: learner-linkup-network
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.20.0/24
