/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DarkModeToggle: typeof import('./src/components/layout/DarkModeToggle.vue')['default']
    DeleteDialog: typeof import('./src/components/students/DeleteDialog.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RegisterModal: typeof import('./src/components/students/RegisterModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
